opencart: 
  build: .
  volumes:
    - oc_epro:/var/www/html/oc_epro
  hostname: opencart
  ports: 
    - "127.0.0.1:8080:80"
  links:
    - db:mysql
db:
  image: mysql
  ports:
    - "127.0.0.1:3307:3306"
  environment:
    MYSQL_USER: admin
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: opencart
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:mysql
  ports:
    - "127.0.0.1:8181:80"
  environment:
    PMA_USER: admin
    PMA_PASSWORD: admin
    PMA_HOST: mysql
